# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点运行，你可以根据需要调整定时规则
  workflow_dispatch:  # 也可以手动触发
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:   
      - name: 克隆仓库
        run: |
          git clone https://${{ secrets.PRIVATE_REPO_PAT }}@github.com/zyth3519/RimeConfig.git

      - name: 下载Release文件 
        run: |
          cd RimeConfig
          wget https://api.github.com/repos/amzxyz/rime_wanxiang/releases -P ./tmp
          
      - name: 比较版本
        id: version
        run: | 
          cd RimeConfig
          local_version=$(cat version.txt)
          remote_version=$(bash get_last_version.sh)
          res=$(bash compare_versions.sh $local_version $remote_version)
          if (( res==2 )) then
            echo "UPDATE_CONFIG=true" >> $GITHUB_ENV
            echo "version=$remote_version" >> $GITHUB_OUTPUT
          fi
          
      - name: 下载配置文件
        if: env.UPDATE_CONFIG == 'true'
        run: |
          cd RimeConfig
          wget  https://github.com/amzxyz/rime_wanxiang/releases/download/${{ steps.version.outputs.version }}/rime-wanxiang-base.zip  -P ./tmp

      - name: 下载词库文件
        run: |
          cd RimeConfig
          wget https://github.com/amzxyz/rime_wanxiang/releases/download/dict-nightly/base-dicts.zip -P ./tmp

      - name: 更新配置
        if: env.UPDATE_CONFIG == 'true'
        run: |
          cd RimeConfig
          7z x ./tmp/rime-wanxiang-base.zip -o./tmp/config
          cp -rf ./tmp/config/* .

      - name: 更新词库
        run: |
          cd RimeConfig
          7z x ./tmp/base-dicts.zip -o./tmp
          cp -rf ./tmp/base-dicts/* dicts

      - name: 判断是否需要更新
        run: |
          cd RimeConfig
          if git status | grep -q "nothing to commit, working tree clean"; then echo 不需要更新; else echo "NEED_PUSH=true" >> $GITHUB_ENV; fi

      - name: Push Main
        if: env.NEED_PUSH == 'true'
        run: |
          cd RimeConfig
          git config user.name "zyth3519"
          git config user.email "zythpang@github.com"
          git add .
          git commit -m "更新配置和词库"
          git push origin ${{ github.ref_name }}

      - name: Push Main
        if: env.NEED_PUSH == 'true'
        run: |
          cd RimeConfig
          git switch android
          git merge main -m "合并Main"
          git push origin android
