# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点运行，你可以根据需要调整定时规则
  workflow_dispatch:  # 也可以手动触发
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:   
      - name: Clone
        run: |
          git clone https://${{ secrets.PRIVATE_REPO_PAT }}@github.com/zyth3519/RimeConfig.git

      - name: Download Releases file
        run: |
          cd RimeConfig
          wget https://api.github.com/repos/amzxyz/rime_wanxiang/releases -P ./tmp
          
      - name: Compare version
        id: version
        run: | 
          cd RimeConfig
          local_version=$(cat version.txt)
          remote_version=$(bash get_last_version.sh)
          res=$(bash compare_versions.sh $local_version $remote_version)
          if (( res==2 )) then
            echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
            echo "version=$remote_version" >> $GITHUB_OUTPUT
          fi
          
      - name: Download last config
        if: env.UPDATE_NEEDED == 'true'
        run: |
          cd RimeConfig
          wget  https://github.com/amzxyz/rime_wanxiang/releases/download/${{ steps.version.outputs.version }}/rime-wanxiang-base.zip  -P ./tmp

      - name: Download last dict
        run: |
          cd RimeConfig
          wget https://github.com/amzxyz/rime_wanxiang/releases/download/dict-nightly/base-dicts.zip -P ./tmp

      - name: Update config
        if: env.UPDATE_NEEDED == 'true'
        run: |
          cd RimeConfig
          7z x ./tmp/rime-wanxiang-base.zip -o./tmp/config
          cp -rf ./tmp/config/* .

      - name: Update dict
        run: |
          cd RimeConfig
          7z x ./tmp/base-dicts.zip -o./tmp
          cp -rf ./tmp/base-dicts/* dicts

      - name: Push
        run: |
          cd RimeConfig
          git config user.name "zyth3519"
          git config user.email "zythpang@github.com"
          git add .
          git commit -m "update config and dict"
          git push origin ${{ github.ref_name }}

